/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "windows.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_EDIT_0     (GUI_ID_USER + 0x04)
#define ID_TEXT_3     (GUI_ID_USER + 0x05)
#define ID_PROGBAR_0     (GUI_ID_USER + 0x07)
#define ID_BUTTON_0     (GUI_ID_USER + 0x08)
#define ID_BUTTON_1     (GUI_ID_USER + 0x09)
#define ID_SPINBOX_0     (GUI_ID_USER + 0x0A)
#define ID_SPINBOX_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_4     (GUI_ID_USER + 0x0C)
#define ID_TIMER_CONVERT_MONITOR (GUI_ID_USER + 0x0D)
#define ID_BUTTON_2     (GUI_ID_USER + 0x0E)
#define ID_SPINBOX_2     (GUI_ID_USER + 0x0F)
#define ID_TEXT_5     (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 214, 5, 400, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 10, 40, 750, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 10, 80, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 10, 130, 445, 30, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4, 10, 190, 300, 30, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5, 10, 250, 300, 30, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 460, 80, 120, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 10, 300, 780, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "StartBtn", ID_BUTTON_0, 30, 365, 200, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BackBtn", ID_BUTTON_1, 550, 365, 200, 100, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "HeaterBtn", ID_BUTTON_2, 280, 365, 200, 100, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 460, 120, 130, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_1, 460, 180, 130, 50, 0, 0x0, 0 },
	{ SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_2, 460, 240, 130, 50, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
WM_HTIMER hTimerValv;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  EDIT_Handle hEdit;
	WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C08000));
	
		hTimerValv = WM_CreateTimer(hItem, ID_TIMER_CONVERT_MONITOR, 100, 0);
	
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "Калибровка клапана:");
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Отбираемый объем 200 мл");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "Отобранный объем, мл");
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetFloatMode(hItem, globalState.vlvclb_state.Q_calc, 0, 1000, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Фактически отобранный объем, мл");
    //
    // Initialization of 'StartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Калибровка");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'BackBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Применить");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
		//
    // Initialization of 'HeaterBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "Нагрев");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Коэффициент k, мл/с");
		//
    // Initialization of 'Q fact'
    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, globalState.vlvclb_state.Q_fact, 0, 1000, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'flow koeff'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetFloatMode(hEdit, Settings.flow_koeff.value, Settings.flow_koeff.min_val, Settings.flow_koeff.max_val, 3, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'TEN 2 power'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Мощность ТЭН 2, %");
		//
    // Initialization of 'TEN 2 power'
    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		SPINBOX_SetStep(hItem, 10);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.pow_heater.value, 0, 1000, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
		
		//
    // Initialization of 'ProgBar'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetFont(hItem, &GUI_FontArial32);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	case WM_TIMER:
		
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			EDIT_SetFloatValue(hItem, globalState.vlvclb_state.Q_calc);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
			PROGBAR_SetValue(hItem, ValveGetOpenCount() * 100 / globalState.vlvclb_state.pulseCount);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
			hEdit = SPINBOX_GetEditHandle(hItem);
			EDIT_SetValue(hEdit, globalState.vlvclb_state.Q_fact);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
			hEdit = SPINBOX_GetEditHandle(hItem);
			EDIT_SetFloatValue(hEdit, Settings.flow_koeff.value);
			
			WM_RestartTimer(pMsg->Data.v, 250);
	
		break;	
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'StartBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				if (GetSubMode() == SMODE_VC_CAL || GetSubMode() == SMODE_VC_ENDSAVE) {
					BUTTON_SetText(hItem, "Калибровка");
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
					BUTTON_SetText(hItem, "Нагрев");
					WM_EnableWindow(hItem);
					SetSubMode(SMODE_VC_STOP);
				}	else {
					BUTTON_SetText(hItem, "Стоп");
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
					WM_DisableWindow(hItem);
					SetSubMode(SMODE_VC_PREPARE);
				}					
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'BackBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				SetStateMode(MODE_NOTHING);
				BeeperOn();
				SaveSettings();
				BeeperOff();
				GUI_EndDialog(pMsg->hWin, SCR_SETTINGS_SEL_CAL);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_BUTTON_2: // Notifications sent by 'HeaterBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				if (GetSubMode() == SMODE_VC_START_HEAT) {
					BUTTON_SetText(hItem, "Нагрев");
					SetSubMode(SMODE_VC_STOP);
				}	else if (GetSubMode() == SMODE_VC_STOP){
					BUTTON_SetText(hItem, "Выкл\nнагрев");
					SetSubMode(SMODE_VC_START_HEAT);
				}					
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Q fact'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
					globalState.vlvclb_state.Q_fact = SPINBOX_GetValue(hItem);
			
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
				hEdit = SPINBOX_GetEditHandle(hItem);
				Settings.flow_koeff.value = EDIT_GetFloatValue(hEdit); // W! need rewrite
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_SPINBOX_2: // Notifications sent by 'TEN 2 power'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
					Settings.rect_set.pow_heater.value = SPINBOX_GetValue(hItem);
			
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateCAlibrationValveWnd(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
