/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "windows.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)
#define ID_TEXT_3    (GUI_ID_USER + 0x04)
#define ID_TEXT_4    (GUI_ID_USER + 0x05)
#define ID_TEXT_5    (GUI_ID_USER + 0x06)
#define ID_TEXT_6    (GUI_ID_USER + 0x07)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x08)
#define ID_SPINBOX_1    (GUI_ID_USER + 0x09)
#define ID_SPINBOX_2    (GUI_ID_USER + 0x0A)
#define ID_SPINBOX_3    (GUI_ID_USER + 0x0B)
#define ID_SPINBOX_4    (GUI_ID_USER + 0x0C)
#define ID_SPINBOX_5    (GUI_ID_USER + 0x0D)
#define ID_BUTTON_0    (GUI_ID_USER + 0x0E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 183, 5, 453, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 10, 60, 390, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 10, 120, 390, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 10, 180, 390, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 10, 240, 390, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 10, 300, 390, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 10, 360, 390, 30, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 400, 50, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_1, 400, 110, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_2, 400, 170, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_3, 400, 230, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_4, 400, 290, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_5, 400, 350, 120, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BackBtn", ID_BUTTON_0, 585, 365, 200, 100, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  EDIT_Handle hEdit;
	WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C08000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Параметры дистилляции");
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Р ТЭНа мин Т куба >70, %");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Скорость отбора, мл/ч");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Объем голов, мл");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Т куба сниж. V отб., С");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Т куба начала отб. хвостов,С");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Т куба завершения, С");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'P TEN min'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		SPINBOX_SetStep(hItem, 10);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.pow_heater.value, Settings.dist_set.pow_heater.min_val, Settings.dist_set.pow_heater.max_val, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'V otbora'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.V_get.value, Settings.dist_set.V_get.min_val, Settings.dist_set.V_get.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'Q golov'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.Q_head.value, Settings.dist_set.Q_head.min_val, Settings.dist_set.Q_head.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 't kub down v otb'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.t_kub_V_down.value, Settings.dist_set.t_kub_V_down.min_val, Settings.dist_set.t_kub_V_down.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 't kub start tail'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.t_kub_get_tail.value, Settings.dist_set.t_kub_get_tail.min_val, Settings.dist_set.t_kub_get_tail.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 't kub off'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_5);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.dist_set.t_kub_off.value, Settings.dist_set.t_kub_off.min_val, Settings.dist_set.t_kub_off.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'BackBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Применить");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
				Settings.dist_set.pow_heater.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
				Settings.dist_set.V_get.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_2: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
				Settings.dist_set.Q_head.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_3: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_3);
				Settings.dist_set.t_kub_V_down.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_4: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_4);
				Settings.dist_set.t_kub_get_tail.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_5: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_5);
				Settings.dist_set.t_kub_off.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'BackBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					BeeperOn();
					SaveSettings(); // Save settings to eeprom
					BeeperOff();
					GUI_EndDialog(pMsg->hWin, SCR_SETTINGS_SEL);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateDistSetWnd(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
