/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "windows.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_2    (GUI_ID_USER + 0x04)
#define ID_TEXT_3    (GUI_ID_USER + 0x05)
#define ID_TEXT_4    (GUI_ID_USER + 0x06)
#define ID_EDIT_1    (GUI_ID_USER + 0x07)
#define ID_EDIT_2    (GUI_ID_USER + 0x08)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x09)
#define ID_SPINBOX_1    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_0    (GUI_ID_USER + 0x0B)
#define ID_TIMER_CONVERT_MONITOR (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 200, 5, 400, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "EditStatus", ID_EDIT_0, 520, 50, 250, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Vremya proparki", ID_TEXT_1, 5, 110, 400, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 5, 170, 400, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 5, 220, 400, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 5, 260, 400, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_t_kub", ID_EDIT_1, 450, 220, 120, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_elapsed_time", ID_EDIT_2, 450, 260, 120, 30, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "SB_time", ID_SPINBOX_0, 450, 100, 120, 50, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "SP_temp", ID_SPINBOX_1, 450, 160, 120, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BackBtn", ID_BUTTON_0, 630, 380, 150, 80, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
WM_HTIMER hTimerClr;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  EDIT_Handle hEdit;
	WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C08000));
		
		hTimerClr = WM_CreateTimer(hItem, ID_TIMER_CONVERT_MONITOR, 250, 0);
		
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Пропарка колоны");
    //
    // Initialization of 'EditStatus'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Vremya proparki'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Время пропарки, мин");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Т куба включения клапанов, С");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Т куба текущая, С");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Время до окончания, мин");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_t_kub'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetFloatMode(hItem, Sensors.t_kub, 0.0, 125.0, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_elapsed_time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		EDIT_SetFont(hItem, &GUI_FontArial32);
		EDIT_SetDecMode(hItem, Settings.clean_set.T_cleaning.value, Settings.clean_set.T_cleaning.min_val, Settings.clean_set.T_cleaning.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //EDIT_SetText(hItem, "123");
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.clean_set.T_cleaning.value, Settings.clean_set.T_cleaning.min_val, Settings.clean_set.T_cleaning.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetTextAlign(hEdit, GUI_TA_LEFT | GUI_TA_VCENTER);
		EDIT_SetDecMode(hEdit, Settings.clean_set.t_open_valve.value, Settings.clean_set.t_open_valve.min_val, Settings.clean_set.t_open_valve.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
		
    //
    // Initialization of 'BackBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выход");
    // USER START (Optionally insert additional code for further widget initialization)
				
    // USER END
    break;
	
	case WM_TIMER:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
				if (GetStateMode() == MODE_RUN_CLS) {
					if (GetSubMode() == SMODE_CLR_HEATING ) {
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
						EDIT_SetText(hItem, "Разогрев");
					} else {
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_ORANGE);
						EDIT_SetText(hItem, "Пропарка");
					}
				} else {
					EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_GREEN);
					EDIT_SetText(hItem, "Завершено");
				}
			
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1); 
				EDIT_SetFloatValue(hItem, Sensors.t_kub);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2); 
				EDIT_SetValue(hItem, globalState.clr_state.T_elapsed);
				/*
				if (GetSubMode() != SMODE_CLR_HEATING) {
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0); 
					
				}
				*/
				WM_RestartTimer(pMsg->Data.v, 250);
		break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'EditStatus'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit_t_kub'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit_elapsed_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'SB_time'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
				Settings.clean_set.T_cleaning.value = SPINBOX_GetValue(hItem);
				globalState.clr_state.T_elapsed = Settings.clean_set.T_cleaning.value;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'SP_temp'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
				Settings.clean_set.t_open_valve.value = SPINBOX_GetValue(hItem);
				globalState.clr_state.T_elapsed = Settings.clean_set.T_cleaning.value;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'BackBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				//SetStateMode(MODE_NOTHING);
				SetSubMode(SMODE_CLR_EXIT);
				BeeperOn();
				SaveSettings();
				BeeperOff();
				GUI_EndDialog(pMsg->hWin, SCR_MAIN);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateRunClrWnd(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
