/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "windows.h"
#include "string.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)
#define ID_TEXT_1    (GUI_ID_USER + 0x05)
#define ID_TEXT_2    (GUI_ID_USER + 0x06)
#define ID_TEXT_3    (GUI_ID_USER + 0x07)
#define ID_TEXT_4    (GUI_ID_USER + 0x08)
#define ID_TEXT_5    (GUI_ID_USER + 0x09)
#define ID_TEXT_6    (GUI_ID_USER + 0x0A)
#define ID_TEXT_7    (GUI_ID_USER + 0x0B)
#define ID_TEXT_8    (GUI_ID_USER + 0x0C)
#define ID_TEXT_9    (GUI_ID_USER + 0x0D)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x0E)
#define ID_EDIT_1    (GUI_ID_USER + 0x0F)
#define ID_EDIT_2    (GUI_ID_USER + 0x10)
#define ID_EDIT_3    (GUI_ID_USER + 0x11)
#define ID_EDIT_4    (GUI_ID_USER + 0x12)
#define ID_EDIT_5    (GUI_ID_USER + 0x13)
#define ID_EDIT_6    (GUI_ID_USER + 0x14)
#define ID_EDIT_7    (GUI_ID_USER + 0x15)
#define ID_EDIT_8    (GUI_ID_USER + 0x16)
#define ID_EDIT_9    (GUI_ID_USER + 0x17)
#define ID_CHECKBOX_0    (GUI_ID_USER + 0x18)
#define ID_TIMER_CONVERT_MONITOR (GUI_ID_USER + 0x19)
#define ID_EDIT_10    (GUI_ID_USER + 0x20)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HTIMER hTimerRunRect;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 200, 5, 400, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "StatusEdit", ID_EDIT_0, 10, 40, 780, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "StartBtn", ID_BUTTON_0, 20, 380, 200, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BackBtn", ID_BUTTON_1, 620, 380, 160, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 5, 90, 315, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 5, 140, 315, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 5, 190, 315, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 5, 240, 315, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 5, 290, 315, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 405, 90, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 405, 190, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 405, 240, 300, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 405, 290, 300, 30, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 670, 90, 120, 50, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit_t_k_v", ID_EDIT_1, 320, 90, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_t_k_n", ID_EDIT_2, 320, 140, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_t_kub", ID_EDIT_3, 320, 190, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_p_kub", ID_EDIT_4, 320, 240, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_Vget", ID_EDIT_5, 320, 290, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_q_fact", ID_EDIT_6, 710, 190, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_pow_kub", ID_EDIT_7, 710, 240, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_ss", ID_EDIT_8, 710, 290, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit_pump", ID_EDIT_9, 300, 380, 150, 30, 0, 0x64, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 10, 325, 500, 40, 0, 0x0, 0 },
	{ EDIT_CreateIndirect, "Edit_water_flow", ID_EDIT_10, 300, 420, 150, 30, 0, 0x64, 0 },// water flow
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  EDIT_Handle hEdit;
	WM_HWIN hItem;
  int     NCode;
  int     Id;
	char buf[40];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00C08000));
		
		hTimerRunRect = WM_CreateTimer(hItem, ID_TIMER_CONVERT_MONITOR, 250, 0);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Ректификация  00:00:00");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'StatusEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "Статус");
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'StartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Начать\nотбор");
		WM_DisableWindow(hItem);
    //
    // Initialization of 'BackBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выход");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "t колоны верх, C");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "t колоны низ, C");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "t куба, C");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Давление в кубе, мм рт");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Скорость отбора, мл/ч");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Объем голов, мл");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Факт. объем, мл");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "P ТЭН, кВт");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Кол-во стопов");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetDecMode(hEdit, Settings.rect_set.Q_sub_head.value, Settings.rect_set.Q_sub_head.min_val, Settings.rect_set.Q_sub_head.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    //
    // Initialization of 'Edit_t_k_v'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetFloatMode(hItem, Sensors.t_kolona_v, 0.0, 125.0, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_t_k_n'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFloatMode(hItem, Sensors.t_kolona_n, 0.0, 125.0, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_t_kub'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetFloatMode(hItem, Sensors.t_kub, 0.0, 125.0, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_p_kub'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetFloatMode(hItem, Sensors.p_kub, Settings.p_min.value, Settings.p_max.value, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_Vget'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetDecMode(hItem, globalState.rect_state.V_get_now, 0, Settings.rect_set.V_get.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_q_fact'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetDecMode(hItem, globalState.rect_state.Q_fact, 0, Settings.rect_set.Q_head.max_val, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_pow_kub'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetFloatMode(hItem, Sensors.heater1_pow + Sensors.heater2_pow, 0.0, 10.0, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_ss'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetDecMode(hItem, globalState.rect_state.ss_count, 0, 1000, 0, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit_pump'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
    EDIT_SetText(hItem, "Выкл");
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00000000));
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//
    // Initialization of 'Edit_water_flow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
    EDIT_SetText(hItem, "0 л/мин");
    EDIT_SetFont(hItem, &GUI_FontArial32);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Пропуск отбора голов");
    CHECKBOX_SetFont(hItem, &GUI_FontArial32);
		CHECKBOX_SetState(hItem, globalState.rect_state.skip_head);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
		
	case WM_TIMER:
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0); // header
			sprintf(buf, "Ректификация %02i:%02i:%02i", globalState.rect_state.time.hour, globalState.rect_state.time.min, globalState.rect_state.time.sec);
			TEXT_SetText(hItem, buf);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1); // t kolona v
			EDIT_SetFloatValue(hItem, Sensors.t_kolona_v);
	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2); // t kolona n
			EDIT_SetFloatValue(hItem, Sensors.t_kolona_n);
				
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3); // t kub
			EDIT_SetFloatValue(hItem, Sensors.t_kub);
	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4); // p kub
			EDIT_SetFloatValue(hItem, Sensors.p_kub);
		
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5); // V get
			EDIT_SetValue(hItem, globalState.rect_state.V_get_now);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6); // Q fact
			EDIT_SetValue(hItem, globalState.rect_state.Q_fact);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7); // power of ten
			EDIT_SetFloatValue(hItem, Sensors.heater1_pow + Sensors.heater2_pow);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8); // start stop
			EDIT_SetValue(hItem, globalState.rect_state.ss_count);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9); // pump state
			if (GetCoolingPumpState()) {
				//EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_GREEN);
				EDIT_SetText(hItem, "Насос вкл");
			} else {
				//EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_RED);
				EDIT_SetText(hItem, "Насос выкл");
			}
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10); //water flow
			sprintf(buf, "%2.1f л/мин", Sensors.f_coolant);
			EDIT_SetText(hItem, buf);
			if (GetCoolingPumpState() && Sensors.f_coolant < 0.5F) {
				EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_RED);
			} else if (GetCoolingPumpState() && Sensors.f_coolant >= 1.5F) {
				EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_GREEN);
			} else {
				EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, EDIT_GetDefaultBkColor(EDIT_CI_ENABLED));
			}
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0); // status
			
			switch(GetSubMode()){
					case SMODE_RECT_PREPARE:					// Подготовка
						EDIT_SetText(hItem, "Подготовка");
						break;
					case SMODE_RECT_PREHEAT:					// Преднагрев
						EDIT_SetText(hItem, "Преднагрев");
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_BLUE);
						break;
					case SMODE_RECT_HEATING:					// Разогрев	
						sprintf(buf, "Разогрев. Стабилизация %i мин", globalState.rect_state.T_elapsed);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_MAGENTA);
						break;
					case SMODE_RECT_WORK_YOUSELF1:					// работа на себя 1	
						sprintf(buf, "Работа на себя %i мин", globalState.rect_state.T_elapsed);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_MAGENTA);
						hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
						WM_EnableWindow(hItem);
						break;
					case SMODE_RECT_GET_HEAD:					// Отбор голов
						sprintf(buf, "Отбор \"голов\" %4.1f мл", globalState.rect_state.Q_fact);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_ORANGE);
						break;
					case SMODE_RECT_GET_SUBHEAD:					// Отбор подголовников
						sprintf(buf, "Отбор \"подголовников\" %4.1f мл", globalState.rect_state.Q_fact);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_ORANGE);
						break;
					case SMODE_RECT_WORK_YOUSELF2:			// Работа на себя 2
						sprintf(buf, "Работа на себя %i мин", globalState.rect_state.T_elapsed);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_ORANGE);
						break;
					case SMODE_RECT_GET_BODY:					// Отбор тела
						sprintf(buf, "Отбор \"тела\" Скорость %4.0f мл/ч", globalState.rect_state.V_get_now);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_ORANGE);
						break;
					case SMODE_RECT_GET_TAIL:					// Отбор хвостов
						sprintf(buf, "Отбор \"хвостов\" Скорость %4.0f мл/ч", globalState.rect_state.V_get_now);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_ORANGE);
						break;
					case SMODE_RECT_END:							// Окончание процесса
						sprintf(buf, "Процесс окончен %i мин", globalState.rect_state.T_elapsed);
						EDIT_SetText(hItem, buf);
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_GREEN);
						break;
					case SMODE_RECT_GET_PAUSE:				// Пауза отбора
						EDIT_SetText(hItem, "Пауза отбора");
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_YELLOW);
						break;
					case SMODE_EMSTOP:	
						EDIT_SetText(hItem, "Аварийный стоп!!!");
						EDIT_SetBkColor(hItem, EDIT_CI_ENABLED,  GUI_RED);
						break;
					}			
			
			WM_RestartTimer(pMsg->Data.v, 250);
		break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'StatusEdit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'StartBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
					if (GetSubMode() == SMODE_RECT_WORK_YOUSELF1) { //  должен быть режим работы на себя 1  SMODE_RECT_WORK_YOUSELF1;
						if (globalState.rect_state.skip_head) {
							SetSubMode(SMODE_RECT_WORK_YOUSELF2);
							globalState.rect_state.T_elapsed = 5; // min 25 
						} else {
							SetSubMode(SMODE_RECT_GET_HEAD);
						}
						BUTTON_SetText(hItem, "Остановить\nотбор");
						//globalState.dist_state.lastSubMode = GetSubMode();
					} else {
						if (GetSubMode() == SMODE_RECT_GET_HEAD || GetSubMode() == SMODE_RECT_GET_SUBHEAD || GetSubMode() == SMODE_RECT_GET_BODY) {
							globalState.dist_state.lastSubMode = GetSubMode();
							SetSubMode(SMODE_RECT_GET_PAUSE);
							BUTTON_SetText(hItem, "Возобновить");
						} else if (GetSubMode() == SMODE_RECT_GET_PAUSE) {
							SetSubMode(globalState.dist_state.lastSubMode);
							BUTTON_SetText(hItem, "Остановить\nотбор");
					}
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'BackBtn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					//SetStateMode(MODE_NOTHING);
					SetSubMode(SMODE_RECT_EXIT);
					GUI_EndDialog(pMsg->hWin, SCR_MAIN);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
   			Settings.rect_set.Q_sub_head.value = SPINBOX_GetValue(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit_t_k_v'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit_t_k_n'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit_t_kub'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit_p_kub'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'Edit_Vget'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'Edit_q_fact'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_7: // Notifications sent by 'Edit_pow_kub'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_8: // Notifications sent by 'Edit_ss'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_9: // Notifications sent by 'Edit_pump'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				 hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
				 globalState.rect_state.skip_head = CHECKBOX_GetState(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateRunRectWnd(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
