/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "windows.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_TEXT_0  (GUI_ID_USER + 0x02)
#define ID_TEXT_8  (GUI_ID_USER + 0x03)
#define ID_BUTTON_1  (GUI_ID_USER + 0x04)
#define ID_BUTTON_2  (GUI_ID_USER + 0x05)
#define ID_TEXT_1  (GUI_ID_USER + 0x06)
#define ID_TEXT_2  (GUI_ID_USER + 0x07)
#define ID_TEXT_3  (GUI_ID_USER + 0x08)
#define ID_TEXT_4  (GUI_ID_USER + 0x09)
#define ID_TEXT_5  (GUI_ID_USER + 0x0A)
#define ID_TEXT_6  (GUI_ID_USER + 0x0B)
#define ID_TEXT_7  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_3  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_4  (GUI_ID_USER + 0x0E)
#define ID_BUTTON_5  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_6  (GUI_ID_USER + 0x10)
#define ID_BUTTON_7  (GUI_ID_USER + 0x11)
#define ID_BUTTON_8  (GUI_ID_USER + 0x12)
#define ID_BUTTON_9  (GUI_ID_USER + 0x13)
#define ID_BUTTON_10  (GUI_ID_USER + 0x14)
#define ID_BUTTON_11  (GUI_ID_USER + 0x15)
#define ID_BUTTON_12  (GUI_ID_USER + 0x16)
#define ID_BUTTON_13  (GUI_ID_USER + 0x17)
#define ID_BUTTON_14  (GUI_ID_USER + 0x18)
#define ID_BUTTON_15  (GUI_ID_USER + 0x19)
#define ID_BUTTON_16  (GUI_ID_USER + 0x1A)
#define ID_BUTTON_17  (GUI_ID_USER + 0x1B)
#define ID_BUTTON_18  (GUI_ID_USER + 0x1C)
#define ID_BUTTON_19  (GUI_ID_USER + 0x1D)
#define ID_BUTTON_20  (GUI_ID_USER + 0x1E)
#define ID_TIMER_CONVERT_MONITOR (GUI_ID_USER + 0x1F)
#define ID_EDIT_0  (GUI_ID_USER + 0x20)
#define ID_EDIT_1  (GUI_ID_USER + 0x21)
#define ID_EDIT_2  (GUI_ID_USER + 0x22)
#define ID_EDIT_3  (GUI_ID_USER + 0x23)
#define ID_EDIT_4  (GUI_ID_USER + 0x24) 
#define ID_SPINBOX_0  (GUI_ID_USER + 0x25)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Tests", ID_WINDOW_0, 0, 1, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 330, 50, 150, 25, 0, 0x64, 0 }, 
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 330, 102, 150, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 330, 215, 350, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 330, 270, 350, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 330, 326, 150, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 330, 160, 450, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 330, 436, 150, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 330, 379, 150, 25, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_8, 250, 10, 300, 30, 0, 0x64, 0 }, // Header text
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 15, 40, 80, 40, 0, 0x0, 0 }, // valve 1 on
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 115, 40, 80, 40, 0, 0x0, 0 }, // valve 1 on 50%
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 215, 40, 80, 40, 0, 0x0, 0 }, // valve 1 off
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 15, 95, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 115, 95, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 215, 95, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 215, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 115, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 15, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 15, 205, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 215, 205, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 15, 260, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 115, 260, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 215, 260, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_14, 15, 315, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_15, 15, 370, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_16, 15, 425, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_17, 215, 315, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_18, 215, 370, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_19, 215, 425, 80, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_20, 620, 400, 100, 60, 0, 0x0, 0 }, // Exit button
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 450, 210, 80, 30, 0, 0x64, 0 }, // curent heater 1
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 450, 265, 80, 30, 0, 0x64, 0 }, // curent heater 2
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_2, 450, 320, 80, 30, 0, 0x64, 0 }, // water flow
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_3, 550, 210, 80, 30, 0, 0x64, 0 }, // power heater 1
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 550, 265, 80, 30, 0, 0x64, 0 }, // power heater 2
	{ SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 650, 250, 120, 50, 0, 0x0, 0 }, // power heater 2 regulator
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
WM_HTIMER hTimerEm;

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  EDIT_Handle hEdit;
	WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Tests'
    //
    hItem = pMsg->hWin;
	
		hTimerEm = WM_CreateTimer(hItem, ID_TIMER_CONVERT_MONITOR, 100, 0);
	
    WINDOW_SetBkColor(hItem, 0x00C08000);
		
		//
    // Initialization of 'Header text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "Тест ИМ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
		//
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Клапан #1");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Клапан #2");
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "ТЭН 1");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "ТЭН 2");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "Насос");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "Клапан #3   А          кВт");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Миксер");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, &GUI_FontArial32);
    TEXT_SetText(hItem, "Вентилятор");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		//
    // Initialization of 'Клапан 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Вкл");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
		//
    // Initialization of 'Клапан 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "50%");
    //
    // Initialization of 'Клапан 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
    //
    // Initialization of 'Клапан 2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "Вкл");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Клапан 2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "50%");
    //
    // Initialization of 'Клапан 2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
    //
    // Initialization of 'Клапан 3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "Выкл");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'Клапан 3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "50%");
    //
    // Initialization of 'Клапан 3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'ТЭН 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'ТЭН 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetText(hItem, "Выкл");
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'ТЭН 2,3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'ТЭН 2,3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "50%");
    //
    // Initialization of 'ТЭН 2,3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
    //
    // Initialization of 'Насос'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Вкл");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
    BUTTON_SetText(hItem, "Выкл");
		//
		// Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_20);
    BUTTON_SetFont(hItem, &GUI_FontArial32);
		//BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, 0x0068f7f9);
    BUTTON_SetText(hItem, "Назад");
    //
    // Initialization of 'curent heater 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetFloatMode(hItem, 0.0, 0.0, 100.0, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES); 
    EDIT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'curent heater 2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1); // 
    EDIT_SetFloatMode(hItem, 0.0, 0.0, 100.0, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
		
		//
    // Initialization of 'water flow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2); // 
    EDIT_SetFloatMode(hItem, Sensors.f_coolant, 0.0, 30.0, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
		
		//
    // Initialization of 'power heater 1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		EDIT_SetFloatMode(hItem, 0.0, 0.0, 10.0, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES); 
    EDIT_SetFont(hItem, &GUI_FontArial32);
    //
    // Initialization of 'power heater 2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4); // 
    EDIT_SetFloatMode(hItem, 0.0, 0.0, 10.0, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFont(hItem, &GUI_FontArial32);
		
		//
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, &GUI_FontArial32);
		hEdit = SPINBOX_GetEditHandle(hItem);
		EDIT_SetDecMode(hEdit, 500, 0, 1000, 1, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
		SPINBOX_SetStep(hItem, 5);
    WM_HideWindow(hItem);
	 
    break;
		
	case WM_TIMER:
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0); 
			EDIT_SetFloatValue(hItem, Sensors.heater1_cur);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1); 
			EDIT_SetFloatValue(hItem, Sensors.heater2_cur);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2); 
			EDIT_SetFloatValue(hItem, Sensors.f_coolant);
	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3); 
			EDIT_SetFloatValue(hItem, Sensors.heater1_pow);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4); 
			EDIT_SetFloatValue(hItem, Sensors.heater2_pow);
			
			// set color for buttons
	/*
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  // TEN 1 ON
			if (R[RW_CMD] & (1<<CMD_BIT_H1E)) {
				BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, 0x000CA00C);
			} else {
				BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, BUTTON_GetDefaultBkColor(BUTTON_CI_UNPRESSED));
			}
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  // TEN 1 OFF
			if (R[RW_CMD] & (1<<CMD_BIT_H1E)) {
				BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, BUTTON_GetDefaultBkColor(BUTTON_CI_UNPRESSED));
			} else {
				BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, 0x0000606D8);
			}
	*/
			WM_RestartTimer(pMsg->Data.v, 250);
	
		break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Клапан 1 вкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOn(VALVE_1);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    
		case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
				#if HEATER2_TEST_MODE == POWER_MAN
   			SetPowerHeaterMan(SPINBOX_GetValue(hItem));
				#else
				SetPowerHeaterAuto(SPINBOX_GetValue(hItem));
				#endif
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;	
			
    case ID_BUTTON_1: // Notifications sent by 'Клапан 1 вкл 50%'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOnPwm(VALVE_1, 1000, 500);	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Клапан 1 выкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOffAll();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Клапан 2 вкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					ValveOn(VALVE_2);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Клапан 2 вкл 50 %'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOnPwm(VALVE_2, 1000, 500);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Клапан 2 выкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOffAll();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Клапан 3 выкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOffAll();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Клапан 3 вкл 50 %'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOnPwm(VALVE_3, 1000, 500);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Клапан 3 вкл'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ValveOn(VALVE_3);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'Button' TEN 1 ON
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				Heater1On();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Button' TEN 1 OFF
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				Heater1Off();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'TEN 2 On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					Heater2On(CMD_MODE_MAN);
					SetPowerHeaterMan(1000); // 100 %
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'TEN 2 on 50 %'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					#if HEATER2_TEST_MODE == POWER_MAN
					Heater2On(CMD_MODE_MAN);
					SetPowerHeaterMan(500); // 50 %
					#else
					Heater2On(CMD_MODE_AUTO);
					SetPowerHeaterAuto(500); // 50 %
					#endif
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
					SPINBOX_SetValue(hItem, 500);
					WM_ShowWindow(hItem);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'TEN 2 off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
				WM_HideWindow(hItem);
				Heater2Off();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by 'Pump on'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				CoolingPumpOn();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by 'Fan on '
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				CoolingFanOn(CMD_MODE_MAN);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'Mixer On '
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				MixerOn();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by 'Pump off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					CoolingPumpOff();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_18: // Notifications sent by 'Fan off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				CoolingFanOff();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_19: // Notifications sent by 'Mixer Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				MixerOff();	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_BUTTON_20: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					ResetCMD();
					ValveOffAll();
					GUI_EndDialog ( pMsg->hWin, SCR_TEST_SEL);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		}	
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTests
*/
WM_HWIN CreateEmTests(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
